#### **Задание #1**

Выполнил: Мирасов Константин Владимирович

ИСУ: 466716

Группа: J3212

#### Импортируем библиотеки и объявляем необходимые константы

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pathlib import Path

In [2]:
RANDOM_STATE: int = 716
TRAIN_SIZE: float = 0.7
TEST_SIZE: float = 0.3
DEGREES_FOR_POLYNOMIALS: list[int] = [1, 2, 3, 4]
PATH_TO_DATASET: Path = Path("../data/fish.csv")

#### Загрузка и обработка датасета `fish.csv`

In [4]:
fish_dataframe = pd.read_csv(PATH_TO_DATASET)
fish_dataframe.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [ ]:
fish_dataframe = pd.get_dummies(fish_dataframe, columns=["Species"], prefix_sep="Specie")
fish_dataframe.head()

   Bream  Parkki  Perch   Pike  Roach  Smelt  Whitefish
0   True   False  False  False  False  False      False
1   True   False  False  False  False  False      False
2   True   False  False  False  False  False      False
3   True   False  False  False  False  False      False
4   True   False  False  False  False  False      False